[Service]
  ServerBindAddr = '0.0.0.0'
  Port = 59980
  ConnectRetries = 3
  HealthCheck = ''
  Labels = [ 'BACnet' ]
  OpenMsg = 'BACnet started'
  ReadMaxLimit = 256
  Timeout = 5000
  CheckInterval = '10s'

[Clients]
  [Clients.Data]
    Host = 'edgex-core-data'
    Port = 59880

  [Clients.Metadata]
    Host = 'edgex-core-metadata'
    Port = 59881

[Device]
  DataTransform = true
  Discovery = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdResultLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = '/profiles'
  SendReadingsOnChanged = true

[Driver]
#  BBMD_ADDRESS = "10.100.22.243"
#  BBMD_PORT = "47809"

#[[DeviceList]]
#  Name = "KMC BAC 5901CE Device"
#  Profile = "BAC-5901CE"
#  Description = "KMC BAC-5901CE Device"
#  Labels = [ "KMC BAC 5901CE Device" ]
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.BACnet-IP]
#      DeviceInstance = 52
#      Port = 47808
